import { type NextPage } from "next";
import Head from "next/head";


const SinglePostPage: NextPage = () => {
 
  return (
    <>
      <Head>
        <title></title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex justify-center h-screen" >
        Post View
      </main>
    </>
  );
};



export default SinglePostPage;

