-- AlterTable
ALTER TABLE `comment` ADD COLUMN `dislikes` INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN `likes` INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN `media` VARCHAR(191) NULL;

-- AlterTable
ALTER TABLE `post` ADD COLUMN `ViewCount` INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN `dislikes` INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN `likes` INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN `postType` ENUM('POST', 'QUESTION') NOT NULL DEFAULT 'POST';
